### ISSUE TITLE
[DEV BRANCH] Crash

### ISSUE THREAD

**Issue by Tempest-5ky** [Thlumyn/clangen#134]
Testing out the development branch, game crashed when clicking "timeskip one moon".
I'm aware that it's in development and therefore unstable! Just wanted to let y'all know.

**crash error trace:**

 Traceback (most recent call last):
  File "c:\Users\Wind\Downloads\games\clangenDEV\clangen-development\main.py", line 259, in <module>
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\Wind\Downloads\games\clangenDEV\clangen-development\scripts\screens.py", line 1493, in on_use
    events_class.one_moon()
  File "c:\Users\Wind\Downloads\games\clangenDEV\clangen-development\scripts\events.py", line 36, in one_moon
    self._extracted_from_one_moon_7(cat)
  File "c:\Users\Wind\Downloads\games\clangenDEV\clangen-development\scripts\events.py", line 112, in _extracted_from_one_moon_7
    self.handle_deaths(cat)
  File "c:\Users\Wind\Downloads\games\clangenDEV\clangen-development\scripts\events.py", line 1036, in handle_deaths
    name + ' lost a life defending ' + other_name +
UnboundLocalError: local variable 'other_name' referenced before assignment

**Comment by KotNad** [comment]
"other_name = str(other_cat.name)" should be added before "if cat.status == 'leader'"

**Comment by Tempest-5ky** [comment]
Yes, I know, and I fixed it on my end. Should I make a pull request for it? I also added some more prefixes/suffixes.

**Comment by Tempest-5ky** [comment]
Never mind! Looks like someone has already done a PR to fix the issue, a couple hours ago.

**Comment by KotNad** [comment]
you shoould go for it, yeah!
