### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by hen** [Thlumyn/clangen#73]
[On development branch]

Clicking Timeskip One Moon - Game crash with this error:

Traceback (most recent call last):
  File "main.py", line 225, in <module>
    game.all_screens[game.current_screen].on_use()
  File "/clangen/scripts/screens.py", line 1007, in on_use 
    events_class.one_moon()
  File "/clangen/scripts/events.py", line 26, in one_moon 
    self._extracted_from_one_moon_7(cat)
  File "/clangen/scripts/events.py", line 67, in _extracted_from_one_moon_7
    self.create_interaction(cat)
  File "/clangen/scripts/events.py", line 592, in create_interaction
    relevant_relationship.start_action()
  File "/clangen/scripts/relationship.py", line 396, in start_action 
    self.link_relationship()
  File "/clangen/scripts/relationship.py", line 387, in link_relationship 
    self.opposit_relationship = list(filter(lambda r: r.cat_to.ID == self.cat_from.ID , self.cat_to.relationships))[0]
IndexError: list index out of range

**Comment by sedgestripe** [comment]
fixed! ty
